"""Adjusted foreign key table name in Ven_Gen_MM

Revision ID: 3290ef5721d0
Revises: ee6a6ec49163
Create Date: 2021-08-13 08:54:19.214140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3290ef5721d0'
down_revision = 'ee6a6ec49163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Ven_Gen_MM_venue_id_fkey', 'Ven_Gen_MM', type_='foreignkey')
    op.create_foreign_key(None, 'Ven_Gen_MM', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Ven_Gen_MM', type_='foreignkey')
    op.create_foreign_key('Ven_Gen_MM_venue_id_fkey', 'Ven_Gen_MM', 'Artist', ['venue_id'], ['id'])
    # ### end Alembic commands ###
