"""Add cascade delete to foreign keys

Revision ID: f5a643c9ced8
Revises: aaf1d4c8289c
Create Date: 2021-08-14 22:25:35.354220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a643c9ced8'
down_revision = 'aaf1d4c8289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Art_Gen_MM_artist_id_fkey', 'Art_Gen_MM', type_='foreignkey')
    op.drop_constraint('Art_Gen_MM_genre_id_fkey', 'Art_Gen_MM', type_='foreignkey')
    op.create_foreign_key(None, 'Art_Gen_MM', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Art_Gen_MM', 'Genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Art_Show_MM_artist_id_fkey', 'Art_Show_MM', type_='foreignkey')
    op.drop_constraint('Art_Show_MM_show_id_fkey', 'Art_Show_MM', type_='foreignkey')
    op.create_foreign_key(None, 'Art_Show_MM', 'Show', ['show_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Art_Show_MM', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Ven_Gen_MM_venue_id_fkey', 'Ven_Gen_MM', type_='foreignkey')
    op.drop_constraint('Ven_Gen_MM_genre_id_fkey', 'Ven_Gen_MM', type_='foreignkey')
    op.create_foreign_key(None, 'Ven_Gen_MM', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Ven_Gen_MM', 'Genres', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Ven_Gen_MM', type_='foreignkey')
    op.drop_constraint(None, 'Ven_Gen_MM', type_='foreignkey')
    op.create_foreign_key('Ven_Gen_MM_genre_id_fkey', 'Ven_Gen_MM', 'Genres', ['genre_id'], ['id'])
    op.create_foreign_key('Ven_Gen_MM_venue_id_fkey', 'Ven_Gen_MM', 'Venue', ['venue_id'], ['id'])
    op.drop_constraint(None, 'Art_Show_MM', type_='foreignkey')
    op.drop_constraint(None, 'Art_Show_MM', type_='foreignkey')
    op.create_foreign_key('Art_Show_MM_show_id_fkey', 'Art_Show_MM', 'Show', ['show_id'], ['id'])
    op.create_foreign_key('Art_Show_MM_artist_id_fkey', 'Art_Show_MM', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint(None, 'Art_Gen_MM', type_='foreignkey')
    op.drop_constraint(None, 'Art_Gen_MM', type_='foreignkey')
    op.create_foreign_key('Art_Gen_MM_genre_id_fkey', 'Art_Gen_MM', 'Genres', ['genre_id'], ['id'])
    op.create_foreign_key('Art_Gen_MM_artist_id_fkey', 'Art_Gen_MM', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
